### ISSUE TITLE
Ошибка базы данных

### ISSUE THREAD

**Issue by LazzyDan** [Laiwer/Mini-Games_Bot#1]
Как я понимаю, нету структуры базы данных

`executor.py [LINE:362] #INFO     [2024-01-16 21:34:20,780]  Bot: Мини-игры [@LazzyDan_Mini_games_bot]
dispatcher.py [LINE:358] #INFO     [2024-01-16 21:34:20,911]  Start polling.
error_handler.py [LINE:37] #ERROR    [2024-01-16 21:34:29,390]  Update: {"update_id": 297949820, "message": {"message_id": 4, "from": {"id": 1205685073, "is_bot": false, "first_name": "Данька", "username": "Lazzy_Dan", "language_code": "ru"}, "chat": {"id": 1205685073, "first_name": "Данька", "username": "Lazzy_Dan", "type": "private"}, "date": 1705430069, "text": "/start", "entities": [{"type": "bot_command", "offset": 0, "length": 6}]}} 
no such table: user
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/container/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/container/handlers/users/start.py", line 33, in bot_start
    if not existe_in_db("user", message.from_user.id):
  File "/home/container/dataBase/base.py", line 12, in existe_in_db
    cursor.execute(f"SELECT user_id FROM {table}")
sqlite3.OperationalError: no such table: user
base_events.py [LINE:1753] #ERROR    [2024-01-16 21:34:29,400]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/container/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('no such table: user')>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/container/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/container/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/container/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/container/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/container/handlers/users/start.py", line 33, in bot_start
    if not existe_in_db("user", message.from_user.id):
  File "/home/container/dataBase/base.py", line 12, in existe_in_db
    cursor.execute(f"SELECT user_id FROM {table}")
sqlite3.OperationalError: no such table: user`

**Comment by Laiwer** [comment]
не добавлен пример базы данных, в следующем комите исправлю, а пока распакуй архив c бд в папку dataBase
[bot_data_base.zip](https://github.com/Laiwer/Mini-Games_Bot/files/13954989/bot_data_base.zip)

**Comment by LazzyDan** [comment]
Спасибо
